import { Rubik, Play } from "next/font/google";
import "./globals.css";

const rubik = Rubik({ subsets: ["latin"], weight: "300", variable: "--font-rubik-300" });
const play = Play({ subsets: ["latin"], weight: "400", variable: "--font-play-400"});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <div className={`${play.className} pageTitle`}>SkillTree/Software/Semester2</div>
          {children}
        <div className={rubik.className}></div>
      </body>
    </html>
  );
}
